Repository dataiku/dataiku-api-client-python, pull requests merged in 2021-12, with the labels that each got.

#193 MLFlow plugin artifacts
  dataikuapi/dss/project.py
  dataikuapi/dss_plugin_mlflow/artifact_repository.py
  dataikuapi/dss_plugin_mlflow/utils.py
  dataikuapi/dssclient.py
Labels: pending-work, team-mielpops

#194 [sc-76604] Fix FM API for azure
  dataikuapi/fm/instances.py
  dataikuapi/fmclient.py
Labels: theme-platform

#191 Add DSS plugin for MLflow
  dataikuapi/dss_plugin_mlflow/__init__.py
  dataikuapi/dss_plugin_mlflow/artifact_repository.py
  dataikuapi/dss_plugin_mlflow/header_provider.py
  dataikuapi/dss_plugin_mlflow/utils.py
  dataikuapi/dssclient.py
Labels: team-mielpops

#190 9.0: import for ansible support
  dataikuapi/dss/tools/codegen.py
  dataikuapi/dssclient.py
Labels: theme-platform

#197 Added documentation on EvaluationRecipeCreator
  dataikuapi/dss/recipe.py
Labels: team-mielpops

#198 Refactor setup_mlflow contextmanager
  dataikuapi/dss_plugin_mlflow/__init__.py
  dataikuapi/dss_plugin_mlflow/utils.py
  dataikuapi/dssclient.py
Labels: team-mielpops

#196 Added a function to retrieve a model from a comparison
  dataikuapi/dss/project.py
Labels: team-mielpops

#161 Chore/dss10 clarify get variable apis
  dataikuapi/dss/admin.py
  dataikuapi/dssclient.py
Labels: theme-platform

#200 Give MLflowHandle the ability to reload artifact_repository_registry
  dataikuapi/dss/project.py
  dataikuapi/dss_plugin_mlflow/utils.py
  dataikuapi/dssclient.py
Labels: team-mielpops

#201 Check server side that a MLflow saved model name is not empty when creating or updating
  dataikuapi/dss/project.py
Labels: team-mielpops
