Repository dataiku/dataiku-api-client-python, pull requests merged in 2022-05, with the labels that each got.

#230 [sc85730] Make absolute imports relative
  dataikuapi/dss/modelcomparison.py
  dataikuapi/dss/modelevaluationstore.py
  dataikuapi/fm/instancesettingstemplates.py
  dataikuapi/fm/virtualnetworks.py
Labels: theme-platform

#222 [sc-80908] new PAPI to retrieve a user's last activity
  dataikuapi/dss/admin.py
  dataikuapi/dss/scenario.py
  dataikuapi/dssclient.py
Labels: theme-platform

#237 Add MLflow export to DSSTrainedPredictionModelDetails
  dataikuapi/dss/ml.py
Labels: team-mielpops

#238 [sc-80976] Add a parameter 'architecture' to the cluster create API
  dataikuapi/dssclient.py
Labels: theme-platform

#227 Add k8s cluster actions
  dataikuapi/dss/admin.py
Labels: theme-platform

#233 feat: FDG API
  dataikuapi/dss/flow.py
  dataikuapi/dss/ml.py
  dataikuapi/utils.py
Labels: theme-designer

#226 [sc58209] Add personal API keys APIs
  dataikuapi/dss/admin.py
  dataikuapi/dssclient.py
Labels: theme-platform

#241 bug fix : no_fail argument passed
  dataikuapi/dss/recipe.py
Labels: team-mielpops
