Repository dataiku/dataiku-api-client-python, pull requests merged in 2022-04, with the labels that each got.

#228 Enfore type check on managed folder in mlflow import
  dataikuapi/dss/savedmodel.py
Labels: team-mielpops

#229 Setting up connection for no verify and client certificate cases
  dataikuapi/dss_plugin_mlflow/utils.py
Labels: team-mielpops

#217 Add support for bundle governance
  dataikuapi/dss/apideployer.py
  dataikuapi/dss/projectdeployer.py
Labels: GovHub

#219 [sc-80919] new PAPI - dataset get full info
  dataikuapi/dss/dataset.py
Labels: theme-platform

#215 [sc-72323] OAuth2 API node - Allow sending a bearer token
  dataikuapi/apinode_client.py
  dataikuapi/base_client.py
Labels: theme-platform

#235 Support passing the managed folder as an id or a Folder in setup_mlflow
  dataikuapi/dss/project.py
  dataikuapi/dss_plugin_mlflow/utils.py
Labels: team-mielpops

#231 MLflow dss flavor
  dataikuapi/dss_plugin_mlflow/artifact_repository.py
  dataikuapi/dss_plugin_mlflow/utils.py
Labels: team-mielpops
