Repository dataiku/dataiku-api-client-python, pull requests merged in 2022-08, with the labels that each got.

#247 client for FM on GCP
  dataikuapi/__init__.py
  dataikuapi/fm/instances.py
  dataikuapi/fm/instancesettingstemplates.py
  dataikuapi/fm/tenant.py
  dataikuapi/fm/virtualnetworks.py
  dataikuapi/fmclient.py
Labels: theme-platform

#225 Python export feature
  dataikuapi/dss/ml.py
  dataikuapi/dss_plugin_mlflow/artifact_repository.py
  dataikuapi/dss_plugin_mlflow/utils.py
Labels: team-mielpops

#255 Path issue windows mlflow plugin
  dataikuapi/dss/managedfolder.py
  dataikuapi/dss_plugin_mlflow/artifact_repository.py
Labels: team-mielpops

#239 Add support for clustering model in API endpoint
  dataikuapi/dss/apiservice.py
Labels: team-mielpops

#256 MlflowHandle with managed_folder.get_id() instead of name when it is a Folder
  dataikuapi/dss_plugin_mlflow/utils.py
Labels: team-mielpops

#254 dataset import: list and import elastic search indices
  dataikuapi/dss/project.py
Labels: theme-intell

#258 [sc-92338] smoother polling strategy
  dataikuapi/dss/job.py
Labels: theme-platform

#261 govern public api fixes
  dataikuapi/govern/admin.py
  dataikuapi/govern/admin_blueprint_designer.py
  dataikuapi/govern/admin_custom_page_editor.py
  dataikuapi/govern/admin_roles_and_permissions_audit.py
  dataikuapi/govern/admin_roles_permissions_editor.py
  dataikuapi/govern/artifact.py
  dataikuapi/govern/artifact_search_handler.py
  dataikuapi/govern/blueprint.py
  dataikuapi/govern/custom_page.py
  dataikuapi/govern/users_container.py
  dataikuapi/govern_client.py
Labels: GovHub

#262 Fix rename move http methods in python client
  dataikuapi/dss/plugin.py
  dataikuapi/dss/project.py
Labels: theme-designer
